//? LOGIN

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_OK = 'LOGIN_REQUEST_OK';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_OK = 'REGISTER_REQUEST_OK';
export const REGISTER_REQUEST_FAIL = 'REGISTER_REQUEST_FAIL';
